# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6SIoDuy1EWcj7EKE2rkaSm3UhXtDs6x
"""

from fastapi import FastAPI, File, UploadFile
from fastapi.responses import JSONResponse
import uvicorn
from PIL import Image
import numpy as np
import io
import tensorflow as tf

# Load the model
model = tf.keras.models.load_model(file_path)

# Initialize FastAPI app
app = FastAPI()

# Define class names
class_names = ['Benign', 'Malignant']  # Change as per your dataset

@app.post("/predict/")
async def predict(file: UploadFile = File(...)):
    try:
        contents = await file.read()
        image = Image.open(io.BytesIO(contents)).resize((256, 256))
        image_array = np.expand_dims(np.array(image) / 255.0, axis=0)

        prediction = model.predict(image_array)
        predicted_class = class_names[int(np.round(prediction[0][0]))]
        confidence = float(prediction[0][0]) if predicted_class == "Malignant" else 1 - float(prediction[0][0])

        return JSONResponse(content={
            "class": predicted_class,
            "confidence": f"{confidence:.2f}"
        })
    except Exception as e:
        return JSONResponse(content={"error": str(e)}, status_code=500)

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/New Folder/skin_cancer_model.keras'

import os
print(os.path.exists(file_path))  # Should output: True if file is found

